name: Release ESMF SDK
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true
env:
  RELEASE_VERSION: ${{ github.event.inputs.release_version }}
permissions: { }
jobs:
  check-preconditions:
    name: Check preconditions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      # Required for Maven
      - name: Set up JDK 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25.0.1'
          overwrite-settings: false

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sanity check version
        if: ${{ !contains( env.RELEASE_VERSION, '-M' ) }}
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          if [[ "${RELEASE_VERSION}" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]
          then
            echo version is valid
          else
            echo release version ${RELEASE_VERSION} is invalid
            exit 1
          fi

  build-macos-aarch64:
    name: Mac build (Apple Silicon)
    needs: [ check-preconditions ]
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25.0.2+10'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb #v5.0.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: |
          export MAVEN_OPTS="-Xmx4096m"
          export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
          # Required for reactor dependencies
          mvn clean install -DskipTests -Dmaven.javadoc.skip=true
          mvn versions:set -DnewVersion=${RELEASE_VERSION}
          mvn versions:commit
          # Actual build of core SDK
          mvn -B -pl '!org.eclipse.esmf:samm-cli' clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
          # Build samm-cli executable jar
          unset JAVA_TOOL_OPTIONS
          mvn -B -pl tools/samm-cli clean verify -Dmaven.wagon.httpconnectionManager.ttlSeconds=60

          # Build native binary
          bundle="samm-cli-${RELEASE_VERSION}"
          mkdir ${bundle}
          curl -Lo jre.tar.gz https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.1%2B8/OpenJDK25U-jre_aarch64_mac_hotspot_25.0.1_8.tar.gz
          tar -xvf jre.tar.gz
          mv ./jdk-25.0.1+8-jre ./${bundle}/jre
          cp tools/samm-cli/target/samm-cli-${RELEASE_VERSION}.jar ./${bundle}/
          cp tools/samm-cli/scripts/macos/run.sh ./${bundle}/
          chmod +x ./${bundle}/run.sh

          curl -Lo warp-packer https://github.com/dgiagio/warp/releases/download/v0.3.0/macos-x64.warp-packer
          if [ "$(sha256sum warp-packer | cut -d' ' -f1)" != "01d00038dbbe4e5a6e2ca19c1235f051617ac0e6e582d2407a06cec33125044b" ]; then
            echo "Warp packer checksum does not match"
            exit 1
          fi
          chmod +x warp-packer

          ./warp-packer --arch macos-x64 --input_dir ${bundle} --exec run.sh --output samm
          chmod a+x samm
          tar cfvz samm-cli-${RELEASE_VERSION}-macos-aarch64.tar.gz samm
        shell: bash

      - name: Upload Mac Apple Silicon binary
        uses: actions/upload-artifact@v7.0.1
        with:
          name: mac-aarch64-artifacts
          path: |
            samm-cli-${{ env.RELEASE_VERSION }}-macos-aarch64.tar.gz

  release:
    name: Release
    needs: [ build-macos-aarch64 ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      issues: write
      pull-requests: write
    steps:
      # Need to checkout here too, so that we have the pom.xml
      # with the deployment info available
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      # Required to have Maven settings.xml set up correctly
      - name: Set up JDK 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25.0.2+10'
          server-id: central
          # The following variables are defined in https://github.com/eclipse-esmf/.eclipsefdn/blob/main/otterdog/eclipse-esmf.jsonnet
          server-username: CENTRAL_SONATYPE_TOKEN_USERNAME
          server-password: CENTRAL_SONATYPE_TOKEN_PASSWORD
          overwrite-settings: false

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25.0.2+10'
          distribution: 'temurin'

      - name: Fetch Mac Apple Silicon Artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: mac-aarch64-artifacts

      - name: Set versions
        continue-on-error: true
        run: |
          release_branch_name=${RELEASE_VERSION%.*}.x
          echo "release_branch_name=$release_branch_name" >> $GITHUB_ENV

          # Set version in pom.xml files
          mvn -B clean install -DskipTests -Dmaven.javadoc.skip=true
          mvn -B versions:set -DnewVersion=${RELEASE_VERSION}
          mvn -B versions:commit
          # Set version in Antora module
          yq eval -i '.version = "${RELEASE_VERSION}"' documentation/developer-guide/antora.yml

      - name: Commit version changes and push to upstream repository
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: ${{ env.release_branch_name }}
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          commit_author: Author <actions@github.com>
          file_pattern: 'documentation/developer-guide/antora.yml pom.xml */pom.xml */*/pom.xml'

      # Full release: Github
      - name: "Create Github release (full)"
        if: ${{ !contains( env.RELEASE_VERSION, '-M' ) }}
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          body: "Release version ${{ env.RELEASE_VERSION }}."
          tag_name: v${{ env.RELEASE_VERSION }}
          target_commitish: ${{ env.release_branch_name }}
          draft: false
          prerelease: false
          files: |
            samm-cli-${{ env.RELEASE_VERSION }}-macos-aarch64.tar.gz
            samm-cli-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: "Notify issues of release their fix is contained in"
        if: ${{ !contains( env.RELEASE_VERSION, '-M' ) }}
        uses: apexskier/github-release-commenter@3bd413ad5e1d603bfe2282f9f06f2bdcec079327 # v1.3.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            Release {release_link} addresses this.

      - name: Trigger Jenkins Job, for signing executable
        shell: bash
        run: |
          DATA='{"repository": {"url": "https://github.com/eclipse-esmf/esmf-sdk", "html_url": "https://github.com/eclipse-esmf/esmf-sdk", "owner": { "name": "ESMF"}}, "pusher": { "name": "GitHub Action", "email": "esmf-dev@eclipse.org"}}'
          SHA1="$(echo -n "${DATA}" | openssl dgst -sha1 -hmac "${WEBHOOK_SECRET}" | sed 's/SHA1(stdin)= //')"
          curl -X POST https://ci.eclipse.org/esmf/github-webhook/ -H "Content-Type: application/json" -H "X-GitHub-Event: push" -H "X-Hub-Signature: sha1=${SHA1}" -d "${DATA}"

      # Full release: Maven Central
      - name: Release to Maven Central
        if: ${{ !contains( env.RELEASE_VERSION, '-M' ) }}
        run: |
          token_header=$(printf "$CENTRAL_USERNAME:$CENTRAL_TOKEN" | base64)
          curl --request POST \
          --header "Authorization: Bearer $token_header" \
          --form bundle=@central-bundle.zip \
          https://central.sonatype.com/api/v1/publisher/upload
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}

      # Milestone release: Write settings to deploy to Github repo
      - name: Write settings.xml
        if: contains( env.RELEASE_VERSION, '-M' )
        uses: DamianReeves/write-file-action@0a7fcbe1960c53fc08fe789fa4850d24885f4d84 # v1.2
        with:
          path: settings.xml
          contents: |
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
               <servers>
                  <server>
                     <id>github</id>
                     <configuration>
                        <httpHeaders>
                           <property>
                              <name>Authorization</name>
                              <value>Bearer ${env.GITHUB_TOKEN}</value>
                           </property>
                        </httpHeaders>
                     </configuration>
                  </server>
                  <server>
                     <id>gpg.passphrase</id>
                     <passphrase>${env.PGP_KEY_PASSWORD}</passphrase>
                  </server>
               </servers>
            </settings>
          write-mode: overwrite

      # Milestone release: Maven deploy to Github
      - name: Publish to Github
        if: contains( env.RELEASE_VERSION, '-M' )
        run: mvn -s ./settings.xml -B clean -pl '!documentation,!tools/samm-cli' deploy -DskipTests -Pmilestone-build,sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}

      # Milestone release: Github
      - name: "Create Github release (milestone)"
        if: contains( env.RELEASE_VERSION, '-M' )
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          body: "Release version ${{ env.RELEASE_VERSION }}."
          tag_name: v${{ env.RELEASE_VERSION }}
          target_commitish: ${{ env.release_branch_name }}
          draft: false
          prerelease: true
          files: |
            samm-cli-${{ env.RELEASE_VERSION }}-macos-aarch64.tar.gz
            samm-cli-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
